service:
  name: aws-apache-to-json

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  memorySize: 128
  region: us-east-1
  runtime: nodejs8.11
  timeout: 120

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:AbortMultipartUpload"
        - "s3:GetBucketLocation"
        - "s3:GetObject"
        - "s3:ListBucket"
        - "s3:ListBucketMultipartUploads"
        - "s3:PutObject"
      Resource: ${file(./resources.yml):s3Buckets}
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:Get*"
        - "logs:PutLogEvents"
      Resource: ${file(./resources.yml):logGroups}
    - Effect: "Allow"
      Action:
        - "logs:CreateLogStream"
      Resource: ${file(./resources.yml):logStreams}

functions:
  processor:
    handler: src/main/node/handler.processor

package:
  exclude:
    - node_modules/aws-sdk/**
    - node_modules/aws-sdk-mock/**
    - node_modules/serverless/**
    - src/main/resources/**
